# Generated by Django 4.1.1 on 2022-10-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта автора')),
                ('description', models.CharField(max_length=2000, verbose_name='Текст записи')),
                ('status', models.CharField(choices=[('Active', 'Активно'), ('Blocked', 'Заблокировано')], default='Active', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
    ]
